"""State the intake rules and what each one cost, as a publishable document."""

import json
from dataclasses import dataclass
from pathlib import Path

from analyzer.crawler.corpus import Corpus, build_corpus
from analyzer.crawler.registry import Crawl

GENERATED_NOTE = (
    "Generated by `mcp-observatory crawl`. Every number below is computed from "
    "the crawl it describes, so this file and the scanned set can never "
    "disagree. Do not edit by hand."
)


@dataclass(frozen=True)
class Coverage:
    """One crawl, reduced to the numbers a reader needs to check our claim.

    Published counts for this ecosystem disagree by a factor of eight, and no
    published methodology states whether duplicate entries are collapsed,
    whether unreachable repositories are dropped, or whether the number counts
    registered names or distinct repositories. Those three choices move the
    figure by more than 20% each. Stating them is the point of this type.
    """

    crawled_at: str
    entries_seen: int
    skipped_without_source: int
    corpus: Corpus

    @classmethod
    def from_crawl(cls, crawl: Crawl, *, crawled_at: str) -> "Coverage":
        return cls(
            crawled_at=crawled_at,
            entries_seen=crawl.entries_seen,
            skipped_without_source=crawl.skipped_without_source,
            corpus=build_corpus(crawl.records),
        )


def render_coverage(coverage: Coverage) -> str:
    """Render the summary that is committed to the repository.

    Deterministic for a given crawl, so a diff here always means the ecosystem
    moved rather than that the document was regenerated.
    """
    corpus = coverage.corpus
    accounted = (
        coverage.skipped_without_source + corpus.entries_collapsed + corpus.repository_count
    )

    dropped_why = (
        "Hosted servers reached over HTTP carry no repository. There is nothing "
        "for a static analyser to read, and we never run a server to find out."
    )
    collapsed_why = (
        "Separately registered names pointing at a repository another entry "
        "already named. Each repository is fetched and scanned once."
    )
    scanned_why = "What the published index is actually about."

    rows = (
        ("Dropped: no source to read", f"{coverage.skipped_without_source:,}", dropped_why),
        ("Collapsed: already counted", f"{corpus.entries_collapsed:,}", collapsed_why),
        (
            "**Scanned: distinct repositories**",
            f"**{corpus.repository_count:,}**",
            scanned_why,
        ),
    )

    reconciliation = (
        f"{coverage.skipped_without_source:,} + {corpus.entries_collapsed:,} + "
        f"{corpus.repository_count:,} = {accounted:,}, against "
        f"{coverage.entries_seen:,} entries seen. The arithmetic closes by "
        "construction: nothing disappears between two numbers."
    )

    offered = (
        f"The registry returned **{coverage.entries_seen:,}** entries. An entry is a "
        "registered name, not a server, and the two are not the same thing."
    )

    collapsing = (
        f"The most-claimed repository carries **{corpus.most_claimed_count:,}** "
        "registered names. Counting names rather than repositories would let a "
        "single publisher set the headline figure. The names are not discarded: "
        "every one is recorded against its repository in the generated corpus, "
        "because a repository published under many names is itself worth reporting."
    )

    lines = [
        "# Coverage",
        "",
        GENERATED_NOTE,
        "",
        f"Crawled at: {coverage.crawled_at}",
        "",
        "## What the registry offered",
        "",
        offered,
        "",
        "## What we scan, and what each rule costs",
        "",
        "| Rule | Entries | Why |",
        "| --- | ---: | --- |",
    ]
    lines += [f"| {label} | {count} | {why} |" for label, count, why in rows]
    lines += [
        "",
        reconciliation,
        "",
        "## Why collapsing matters",
        "",
        collapsing,
        "",
    ]
    return "\n".join(lines)


def write_corpus(destination: Path, coverage: Coverage) -> None:
    """Write the full corpus, which is the evidence behind the summary.

    Not committed. It is several megabytes and would produce thousands of diff
    lines nightly, while the committed summary is the part a reviewer reads.
    Anyone who wants to check the summary regenerates this and compares.
    """
    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "crawled_at": coverage.crawled_at,
        "entries_seen": coverage.entries_seen,
        "skipped_without_source": coverage.skipped_without_source,
        **coverage.corpus.to_dict(),
    }
    destination.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
